export const AUTH_REQUEST = "AUTH_REQUEST"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_ERROR = "AUTH_ERROR"
export const AUTH_LOGOUT = "AUTH_LOGOUT"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_ERROR = "REGISTER_ERROR"

export const CHECK_EMAIL_REQUEST = "CHECK_EMAIL_REQUEST"
export const CHECK_EMAIL_SUCCESS = "CHECK_EMAIL_SUCCESS"
export const CHECK_EMAIL_ERROR = "CHECK_EMAIL_ERROR"
