export const USER_REQUEST = "USER_REQUEST"
export const USER_SUCCESS = "USER_SUCCESS"
export const USER_ERROR = "USER_ERROR"

export const CHANGE_DATA_REQUEST = "CHANGE_DATA_REQUEST"
export const CHANGE_DATA_SUCCESS = "CHANGE_DATA_SUCCESS"
export const CHANGE_DATA_ERROR = "CHANGE_DATA_ERROR"


export const ALL_USERS_REQUEST = "ALL_USERS_REQUEST"
export const ALL_USERS_SUCCESS = "ALL_USERS_SUCCESS"
export const ALL_USERS_ERROR = "ALL_USERS_ERROR"

export const FORGET_PASSWORD_REQUEST = "FORGET_PASSWORD_REQUEST"
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS"
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR"

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST"
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR"
export const CLEAR_RESET_TOKEN = "CLEAR_RESET_TOKEN"

export const SEND_MESSAGE = "SEND_MESSAGE"
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS"
export const SEND_MESSAGE_ERROR = "SEND_MESSAGE_ERROR"

export const GET_MESSAGES = "GET_MESSAGES"
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS"
export const GET_MESSAGES_ERROR = "GET_MESSAGES_ERROR"

export const UPDATE_USERNAME = "UPDATE_USERNAME"
